; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
build_flags=
	-D NETWIZARD_USE_ASYNC_WEBSERVER=1
	-D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
lib_compat_mode = strict
lib_ldf_mode = deep   ; This line may or may not be neccessary depending on your project
lib_deps = 
	esp32async/ESPAsyncWebServer@^3.6.0
	mobizt/ReadyMail@^0.4.2
	ayushsharma82/NetWizard@^1.2.2
